spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stockSplice
    username: vishdev1
    password: Vishwa@24
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  info:
    env:
      enabled: true
    app:
      name: Stock service Application
      description: Stock service Application for Stocks trading
      version: 1.0.0
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    env:
      show-values: "ALWAYS"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
