spring:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect        # Match your DB version

  datasource:
    url : jdbc:mysql://127.0.0.1:3306/stockSplice           # database name
    username: vishdev1                                               #${root}
    password: Vishwa@24                                              #${secret}
    #driver-class-name: com.mysql.cj.jdbc.Driver           # Optional—Spring Boot often auto-detects

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  boot:
    refresh-message: last updated on 09/27/2025 5:39 pm IST. 
    
server:
  port : 8081                                              # Optional—default is 8080

management:
  info:
    env:
      enabled: true
    app:
      name: Stock Fundamentals Application
      description: Stock fundamentals Application for Fundamentals & Overview
      version: 1.0.0

  endpoints:
    web:
      exposure:
        include: ["*"]

  endpoint:
    env:
      show-values: "ALWAYS"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/






