spring:

  config:
    activate: 
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect        # Match your DB version

  datasource:
    url : jdbc:mysql://host.docker.internal:3306/stockSplice           # database name
    username: vishdev1                                               #${root}
    password: Vishwa@24                                              #${secret}
    #driver-class-name: com.mysql.cj.jdbc.Driver           # Optional—Spring Boot often auto-detects

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    #host: localhost
    port: 5672
    username: guest
    password: guest
    
  boot:
    refresh-message: last updated on ... loaded from docker profile 10/18/2025 00.00 am IST. 
    
  cloud:
    bus:
      enabled: true
      
server:
  port : 8081                                              # Optional—default is 8080

management:
  info:
    env:
      enabled: true
    app:
      name: Stock Service Application
      description: Stock Service 
      version: 1.0.0
  tracing: 
    sampling: 
      probability: 1.0         # Sample 100% of requests for tracing
    zipkin: 
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans       #if the env variable doesn't exist then it fall back to http://localhost:9411

  endpoints:
    web:
      exposure:
        include: ["*"]      

  endpoint:
    env:
      show-values: "ALWAYS"
    health:
      show-details: ALWAYS

  health:
    circuitbreaker:
      enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  #circuitbreaker:
  #  instances:
  #    stock-service:
  #      registerHealthIndicator: true
  #      failureRateThreshold: 50
  #      minimumNumberOfCalls: 10
  #      automaticTransitionFromOpenToHalfOpenEnabled: true
  #      waitDurationInOpenState: 5s
  #      permittedNumberOfCallsInHalfOpenState: 3
  #      slidingWindowSize: 10
  #      slidingWindowType: COUNT_BASED
  retry:
    instances: 
      stock-service: 
        registerHealthIndicator: true 
        maxAttempts: 10
        waitDuration: 10s
        
      
logging:
  level:
    org.springframework.web: DEBUG  # Enable detailed web logs
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"  # Enrich logs with trace/span IDs
